apiVersion: batch/v1
kind: Job
metadata:
  name: forming
  namespace: moon
spec:
  template:
    metadata:
      name: forming
    spec:
      containers:
      - name: forming
        image: wukongsun/moon_forming:v1.3
        env:
        - name: POPULATE_ARGS
          value: "--verbose" # debug mode: --debug
        volumeMounts:
        - name: config-volume
          mountPath: /etc/moon
        - name: test-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: moon-config
      - name: test-volume
        hostPath:
          path: tests/functional/scenario_enabled
          type: Directory
      restartPolicy: Never
      #backoffLimit: 4