apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: moon
  name: keystone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keystone
    spec:
      hostname: keystone
      containers:
      - name: keystone
        image: asteroide/keystone:mitaka
        env:
        - name: KEYSTONE_HOSTNAME
          value: "varuna"
        - name: KEYSTONE_PORT
          value: "30006"
        ports:
        - containerPort: 35357
          containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: keystone
  namespace: moon
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30006
  selector:
    app: keystone
  type: NodePort
